bookshelf/main/forms.py
import datetime
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    TextAreaField,
    DateTimeField,
    HiddenField,
    PasswordField,
)
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo


class NullableDateTimeField(DateTimeField):
    """Modify DateField to allow for Null values"""

    def process_formdata(self, valuelist):
        # Bypasses wtForms validation for blank datetime field.
        if valuelist:
            date_str = " ".join(valuelist).strip()
            if date_str == "":
                self.data = None
                return
            try:
                self.data = datetime.datetime.strptime(date_str, self.format)
            except ValueError:
                self.data = None
                raise ValueError(self.gettext("Not a valid date value"))


class SearchForm(FlaskForm):
    search = StringField("Search", validators=[DataRequired()])


class ReviewForm(FlaskForm):
    rating = HiddenField("Rating", validators=[DataRequired()])
    review_title = StringField("Headline")
    review_content = TextAreaField("Review")
    date_started = NullableDateTimeField("Date Started", format="%m/%d/%Y")
    date_finished = NullableDateTimeField("Date Finished", format="%m/%d/%Y")

    def validate_date_finished(self, date_finished):
        if self.date_started.data and date_finished.data:
            if self.date_started.data > date_finished.data:
                print("Date finished must be greater than or equal to date started")
                raise ValidationError(
                    "Date finished must be greater than or equal to date started."
                )

        elif self.date_started.data or date_finished.data:
            print("missing date")
            raise ValidationError("If setting read dates, both dates are required.")


class EditProfileForm(FlaskForm):
    display_name = StringField("Name", validators=[])
    email = StringField("Email", validators=[Email(message="Invalid Email Address.")])
    password = PasswordField(
        "Password",
        validators=[EqualTo("confirm_password", message="Passwords must match.")],
    )
    confirm_password = PasswordField("Confirm Password", validators=[])

bookshelf/__init__.py
import os
from flask import Flask

from bookshelf.firebase_wrapper import Firebase

# Global Objects
firebase = Firebase()

config_name = os.environ.get("FLASK_CONFIG", "production")


def create_app(config_name=config_name):
    """Create an application instance with the desired configuration.

    Also where extentions and blueprints are registered with the instance.

    Args:
        config_name (str): Name of configuration type. For config to work,
            a docker-compose .yml file, and a config .json file for the config
            must exist.

    Returns:
        Flask App Object: Flask application instance.
    """
    app = Flask(__name__)
    config_module = f"config.{config_name.capitalize()}Config"

    app.config.from_object(config_module)

    # Initialize firebase
    firebase.init_app(
        app.config.get("GOOGLE_APPLICATION_CREDENTIALS", None),
        app.config.get("WEB_API_KEY", None),
    )

    # Register Blueprints
    from bookshelf.main.routes import bp as books_bp
    from bookshelf.auth.routes import bp as auth_bp

    app.register_blueprint(books_bp)
    app.register_blueprint(auth_bp)

    # Test Route
    @app.route("/hello")
    def hello():
        return f"Hello {__name__}"

    return app

bookshelf/main/routes.py
from datetime import datetime
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    jsonify,
    url_for,
    session,
    flash,
)
from .forms import ReviewForm, EditProfileForm
from bookshelf import firebase
import bookshelf.google_books as google_books
import bookshelf.db_maint as db_maint


auth = firebase.auth()
firestore = firebase.firestore()

bp = Blueprint("books", __name__)


@bp.route("/", methods=["GET"])
@bp.route("/index", methods=["GET"])
def index():
    """Display index.html template with user reviews."""
    books = firestore.get_collection_group(
        "books", order_by=("last_updated", "DESCENDING")
    )

    return render_template("index.html", title="bookshelf | home", books=books)


@bp.route("/profile/<user_id>", methods=["GET"])
@auth.login_required
def profile(user_id):
    """Display profile.html template with user data.

    Displays user accont data, books reading and ratings for books read.
    If the user is the logged in user, the user is allowed to edit their
    information and reviews.

    Args:
        user_id (str): User ID for user who's profile is being viewed.

    """
    user = firestore.get_document(f"users/{user_id}")
    books = firestore.get_collection(f"users/{user_id}/books")
    books_reading = [book for book in books if "date_rated" not in book]
    books_read = [book for book in books if "date_rated" in book]

    if user_id == session["_user"]["uid"]:
        active_user = True
    else:
        active_user = False

    return render_template(
        "profile.html",
        title=f"bookshelf | {user['display_name']}",
        user=user,
        books_reading=books_reading,
        books_read=books_read,
        active_user=active_user,
        user_id=user_id,
    )


@bp.route("/profile/edit/<user_id>", methods=["GET", "POST"])
@auth.login_required
def edit_profile(user_id):
    """Display edit_profile.html template for GET request and process form
    submitted form data for POST requests.

    User information can only be changed for users registered with email.
    Users using google login are unable to edit their data.

    Args:
        user_id (str): User ID for user who's profile is being viewed.

    """
    auth_user = auth.get_user(user_id)
    data = {"display_name": auth_user.display_name}
    providers = auth_user._data["providerUserInfo"]
    email_provider = False

    for provider in providers:
        if provider["providerId"] == "password":
            email_provider = True
            data["email"] = auth_user.email

    form = EditProfileForm(data=data)

    if form.validate_on_submit():
        update_data = {}

        if form.data["email"] != "":
            update_data["email"] = form.data["email"]

        if form.data["password"] != "":
            update_data["password"] = form.data["password"]

        if form.data["display_name"] != "":
            update_data["display_name"] = form.data["display_name"]

        if email_provider:
            try:
                # Update data in Firebase Auth.
                auth_user = auth.update_user(user_id, update_data)
            except ValueError as v:
                # Display any errors to the user. The ValueError will handle
                # Password errors.
                flash(v)
            except Exception as e:
                # TODO: Add specific error handling.
                print(f"Auth Profile Update Error: {e}")
                flash(e)
            else:
                try:
                    # If Firebase Auth successfully updates, update the user
                    # information in Firestore.
                    db_user_data = update_data
                    if "password" in db_user_data:
                        del db_user_data["password"]
                    db_user_data["last_updated"] = datetime.now()
                    firestore.update_document(f"users/{auth_user.uid}", db_user_data)
                    if "display_name" in update_data:
                        db_maint.update_user_data_in_books(auth_user.uid, db_user_data)
                except Exception as e:
                    # TODO: Add specific error handling.
                    print(f"User Database Error: {e}")
                    flash(
                        "A problem arouse while trying to update your profile. Please try again."
                    )

            # Update session data.
            for k, v in session["_user"].items():
                if k in update_data and v != update_data[k]:
                    session["_user"][k] = update_data[k]

        return redirect(url_for("books.profile", user_id=user_id))
    return render_template(
        "edit_profile_form.html",
        title=f"bookshelf | edit | {session['_user']['display_name']}",
        form=form,
        email_provider=email_provider,
    )


@bp.route("/books/search", methods=["GET"])
def search():
    """Display search.html template with book search results."""
    books = google_books.get_books(request.args.get("q"))

    return render_template("search.html", title="bookshelf | Search", books=books)


@bp.route("/books/<book_id>", methods=["GET"])
def book_details(book_id):
    """Display book_detail.html template with user review data.

    If the logged in user has not read the book, they are given the option
    to rate the book by giving it a start rating that will pass to the
    new_review route, leave a review, or mark as reading.

    If the user is currently reading the book, the date started will be
    displayed for the user.

    If the user has read the book, their review will be displayed above
    all other user reviews.

    Args:
        book_id (str): Book Id from google books for the book.

    """
    book = google_books.get_book(book_id)
    book_user_info = None

    if "_user" in session:
        book_user_info = firestore.get_document(
            f"users/{session['_user']['uid']}/books/{book_id}"
        )

    book_reviews = firestore.get_collection_group(
        "books", filters=[("bid", "==", book_id)]
    )

    return render_template(
        "book_details.html",
        title=f"bookshelf | {book['volumeInfo']['title']}",
        book=book,
        book_user_info=book_user_info,
        book_reviews=book_reviews,
    )


@bp.route("/books/review/new/<book_id>", methods=["GET", "POST"])
@auth.login_required
def new_review(book_id):
    """Display book_review.html template for GET request and process new
    review for POST request.

    Args:
        book_id (str): Book Id from google books for the book.

    """
    rating = int(request.args.get("rating", 0))
    form = ReviewForm(rating=rating)
    book = google_books.get_book(book_id)

    if form.validate_on_submit():
        data = {
            "uid": session["_user"]["uid"],
            "display_name": session["_user"]["display_name"],
            "bid": book_id,
            "title": book["volumeInfo"]["title"],
            "authors": book["volumeInfo"]["authors"],
            "cover_url": book["volumeInfo"]["imageLinks"]["thumbnail"],
            "date_rated": datetime.now(),
            "last_updated": datetime.now(),
            "rating": int(form.data["rating"]),
            "review_title": form.data["review_title"],
            "review_content": form.data["review_content"],
            "date_started": form.data["date_started"],
            "date_finished": form.data["date_finished"],
        }
        firestore.set_document(f"users/{data['uid']}/books/{book_id}", data)

        return redirect(url_for("books.book_details", book_id=book_id))

    book_user_info = firestore.get_document(
        f"users/{session['_user']['uid']}/books/{book_id}"
    )

    if book_user_info and "date_started" in book_user_info:
        form.date_started.data = book_user_info["date_started"]

    return render_template(
        "review_form.html",
        title=f"bookshelf | New Review | {book['volumeInfo']['title']}",
        form=form,
        book=book,
        rating=rating,
    )


@bp.route("/books/review/edit/<book_id>", methods=["GET", "POST"])
@auth.login_required
def edit_review(book_id):
    """Display review_form.html with current review data for GET request
    and process updated review data for POST request.

    Args:
        book_id (str): Book Id from google books for the book.

    """
    book = google_books.get_book(book_id)
    user_review = firestore.get_document(
        f"users/{session['_user']['uid']}/books/{book_id}"
    )
    review_data = {
        "rating": user_review["rating"],
        "review_title": user_review["review_title"],
        "review_content": user_review["review_content"],
        "date_started": user_review["date_started"],
        "date_finished": user_review["date_finished"],
    }
    form = ReviewForm(data=review_data)

    if form.validate_on_submit():
        update_data = {
            "last_updated": datetime.now(),
            "rating": int(form.data["rating"]),
            "review_title": form.data["review_title"],
            "review_content": form.data["review_content"],
            "date_started": form.data["date_started"],
            "date_finished": form.data["date_finished"],
        }
        firestore.update_document(
            f"users/{session['_user']['uid']}/books/{book_id}", update_data
        )
        return redirect(url_for("books.book_details", book_id=book_id))

    return render_template(
        "review_form.html", form=form, book=book, rating=user_review["rating"]
    )


@bp.route("/reading", methods=["POST"])
@auth.login_required
def reading():
    """Process AJAX request to set book status as reading.

    Sets the books as reading at the time the button is pressed. At this
    point the data can't be updated until the review when the user can
    modify the date started field in the form.

    Returns:
        JSON: status of 'success' with the start date or status of
            'unable to process' for preocessing failures.

bookshelf/routes.py
from flask import Flask, Blueprint, render_template, redirect, request, jsonify, json, url_for

from .forms import SearchForm, ReviewForm
from .google_books import get_book
from html import unescape
bp = Blueprint('books', __name__)

@bp.route('/search', methods=['GET'])
def search():
    form = SearchForm()
    return render_template('search.html', title='Find A Book', form=form)

@bp.route('/book/<book_id>', methods=['GET'])
def book_details(book_id):
    book = get_book(book_id)
    #print(unescape(book['volumeInfo']['description']))
    return render_template('book_details.html', book=book)

@bp.route('/review/new/<book_id>', methods=['GET', 'POST'])
def new_review(book_id):
    form = ReviewForm()
    book = get_book(book_id)
    rating = request.args.get('rating')
    if rating:
        rating = int(rating)
    else:
        rating = 0
    print(rating)
    print(form.data)
    if form.validate_on_submit():
        print(form.data)
        return redirect(url_for('books.book_details', book_id=book_id))
    return render_template('review_form.html', form=form, book=book, rating=rating)


@bp.route('/test')
def test():
    return ("<p>This is a test</p>")

bookshelf/templates/base.html
<!DOCTYPE html>
    <html lang="en">
        <head> 
            <!--Let browser know website is optimized for mobile-->
            <meta name="viewport" content="width=device-width, initial-scale=1.0", charset="UTF-8"/>
            {% block meta %}{% endblock %}
            <!--Import Google Icon Font-->
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            <!-- Compiled and minified CSS -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
            <!--Custom CSS-->
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
            <!--Font Awesome
            <script src="https://kit.fontawesome.com/1dadc7aeb9.js" crossorigin="anonymous"></script>-->
            {% block head_scripts %}{% endblock %}
            {% block style %}{% endblock %}
            <title>{% block title %}{% endblock %}</title>
        </head>
        <body>
            {% include 'navbar.html' %}
            {% block content %}{% endblock %}
            <!--JavaScript at end of body for optimized loading-->
            <!-- Compiled and minified JavaScript -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
            <script>
                // Initialize materialize functions
                $( document ).ready(function() {
                    // Navbar sub items
                    $(".dropdown-trigger").dropdown();
                    // Navbar sidenav
                    //$(".sidenav").sidenav();
                });

            </script>

            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    var elems = document.querySelectorAll('.sidenav');
                    var instances = M.Sidenav.init(elems);
                });
            </script>
            {% block body_scripts %}{% endblock %}
            {% block mobile %}{% endblock %}
        </body>
    </html>

bookshelf/templates/navbar.html
{% if session['_user'] %}
    <!-- Navbar dropdown list -->
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="{{ url_for('books.profile', user_id=session['_user']['uid']) }}">Profile</a></li>
        <li><button id="btnLogoutMobile" class="btn-logout">Logout</button></li>
    </ul>
    
    {% endif %}
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <div class="row">
                <div class="col s12 m3 ">
                    <a href="{{ url_for('books.index') }}" class="brand-logo"> <i class="material-icons">import_contacts</i>bookshelf</a>
                    <a href="#" data-target="mobile-sidebar" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                </div>
                <div class="col s12 m6 ">                
                    <div class="nav-search grey lighten-4 hide-on-med-and-down">
                        <form action="{{ url_for('books.search') }}" method="get">
                            <div class="col s1" >
                                <button class="nav-search-submit" type="submit"><i class="search-icon material-icons prefix">search</i></button>
                            </div>
                            <div class="col s11">
                                <input type="search" name="q" placeholder="Title, Author, ISBN, etc..." id="" class="no-focus" required >
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col s12 m3 ">
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        {% if session['_user'] %}
                        <li><a href="{{ url_for('books.index') }}">Home</a></li>                    
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{ session['_user']['display_name'] }}<i class="material-icons right">arrow_drop_down</i></a></li>
                        {% else %}
                        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- Sidenav for nav collapse -->
    <ul id="mobile-sidebar" class="sidenav">
        <li>
            <form action="{{ url_for('books.search') }}" method="get">
                <div class="input-field grey lighten-4">
                    <input type="search" name="q" placeholder="Title, Author, ISBN, etc..." required>
                    <label class="label-icon" for="search"><i class="material-icons search-icon">search</i></label>
                </div>         
            </form>
        </li>
        
        {% if session['_user'] %}
            <li><a href="{{ url_for('books.index') }}">Home</a></li>   
            <li><a href="{{ url_for('books.profile', user_id=session['_user']['uid']) }}">Profile</a></li>
            <li><button id="btnLogout" class="btn-logout">Logout</button></li>
        {% else %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
        {% endif %}
    </ul>
{% if session['_user'] %}
    {% block body_scripts %}
        <script src="{{ url_for('static', filename='scripts/logout.js') }}"></script>
    {% endblock %}
{% endif %}

bookshelf/templates/profile.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m10 offset-m1 user-info">
                <div class="col s12 m2 center-align">
                    {% if 'photo_url' in user %}
                        <img class="user-img" src="{{ user.photo_url }}" alt="{{ user.display_name }} photo">    
                    {% else %}
                        <img class="user-img" src="https://via.placeholder.com/150" alt="{{ user.display_name }} photo">
                    {% endif %}
                    <!-- Aggregate Review/Rating Info - Future Upgrade -->
                    <!--<div class="user-stats">
                        13 Ratings (4.00 avg)
                        5 Reviews
                    </div>-->
                </div>
                <div class="col s12 m10">
                    <span class="profile-user-name">{{ user.display_name }}</span>
                    {% if active_user %}<span class="edit-profile"><a href="{{ url_for('books.edit_profile', user_id=user_id) }}">(edit profile)</a></span>{% endif %}
                    <div class="divider"></div>
                    Joined {{ user['created'].strftime('%B %d, %Y')}} <!--last Active this month--> <!--Add later. Requires databse update on login for last logged in-->
                </div>
            </div>
        </div>
        {% if books_reading %}
            <!-- User Currently Reading -->
            <div class="row section-header">
                <div class="col s12 m10 offset-m1">
                    CURRENTLY READING:
                </div>
            </div>            
            {% for book in books_reading %}
                {% if 'date_rated' not in book %}
                    <div class="row">
                        <div class="col s12 m10 offset-m1">
                            <div class="card">
                                <div class="card-content">
                                    <div class="row">
                                        <div class="card-title col s12">
                                            Started Reading On {{ book.date_started.strftime('%b %d, %Y')}}                                 
                                        </div>  
                                        <div class="col s12 divider"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 m2">
                                            {% if 'cover_url' in book %}
                                                <a href="{{ url_for('books.book_details', book_id=book.bid) }}"><img class="cover-img" src="{{ book.cover_url }}" alt="{{ book.title }} cover" ></a>
                                            {% else %}
                                                <a href="{{ url_for('books.book_details', book_id=book.bid) }}"><img class="cover-img" src="https://via.placeholder.com/150" alt="{{ book.title }} cover"></a>
                                            {% endif %}
                                        </div>
                                        <div class="col s12 m10">
                                            <div class="col s12 m6">
                                                <span class="book-title"><h5><a href="{{ url_for('books.book_details', book_id=book.bid) }}">{{ book.title }}</a></h5></span>
                                                by {{ ', '.join(book.authors) }}
                                            </div>
                                            <div class="col s12 m6 right-align card-rating-align">
                                                <a href="{{ url_for('books.new_review' , book_id=book.bid, rating=1) }}"><i value="1" class="material-icons star-icon set-review" >star_border</i></a>
                                                <a href="{{ url_for('books.new_review' , book_id=book.bid, rating=2) }}"><i value="2" class="material-icons star-icon set-review" >star_border</i></a>
                                                <a href="{{ url_for('books.new_review' , book_id=book.bid, rating=3) }}"><i value="3" class="material-icons star-icon set-review" >star_border</i></a>
                                                <a href="{{ url_for('books.new_review' , book_id=book.bid, rating=4) }}"><i value="4" class="material-icons star-icon set-review" >star_border</i></a>
                                                <a href="{{ url_for('books.new_review' , book_id=book.bid, rating=5) }}"><i value="5" class="material-icons star-icon set-review" >star_border</i></a><br>                    
                                                <a href="{{ url_for('books.new_review', book_id=book.bid) }}" class="status-btn waves-effect waves-light btn center-align">Leave Review</a>                                        
                                            </div>
                                        </div> 
                                    </div>                    
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if books_read %}
            <!-- User Read -->
            <div class="row section-header">
                <div class="col s12 m10 offset-m1">
                    BOOKS READ:
                </div>
            </div>
            {% for book in books_read %}
                {% if 'date_rated' in book %}
                    <div class="row">
                        <div class="col s12 m10 offset-m1">
                            <div class="card">
                                <div class="card-content">
                                    <div class="row">
                                        <div class="card-title col s12">
                                            Rated it                                    
                                            {% for i in range(book.rating | int) %}
                                                <i class="material-icons star-icon" >star</i>
                                            {% endfor %}
                                            {% for j in range(book.rating | int, 5) %}
                                                <i class="material-icons star-icon" >star_border</i>
                                            {% endfor %}  
                                            on {{ book.date_rated.strftime('%b %d, %Y') }}
                                            {% if active_user %}                                            
                                                <a href="{{ url_for('books.edit_review', book_id=book.bid) }}"><i class="material-icons create-icon">create</i></a>                                            
                                            {% endif %}
                                        </div>    
                                        <div class="col s12 divider"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 m2">
                                            {% if 'cover_url' in book %}
                                                <a href="{{ url_for('books.book_details', book_id=book.bid) }}"><img class="cover-img" src="{{ book.cover_url }}" alt="{{ book.title }} cover" ></a>
                                            {% else %}
                                                <a href="{{ url_for('books.book_details', book_id=book.bid) }}"><img class="cover-img" src="https://via.placeholder.com/150" alt="{{ book.title }} cover"></a>
                                            {% endif %}                                        
                                        </div>
                                        <div class="col s12 m10"></div>
                                        <div class="col s12">
                                            <span class="book-title"><h5><a href="{{ url_for('books.book_details', book_id=book.bid) }}">{{ book.title }}</a></h5></span>by {{ ', '.join(book.authors) }}
                                        </div>
                                        <div class="col s12 divider"></div>
                                        <div class="col s12 review-title">
                                            {{ book.review_title }}
                                        </div>
                                        <div class="col s12 review-content">
                                            {{ book.review_content }}
                                        </div>           
                                    </div> 
                                </div>                    
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}   
        {% endif %} 
    </div>
{% endblock %}


{% block body_scripts %}
<script>
    // Star Rating
    const ratingField = document.getElementById("rating");
    const starElements = document.getElementsByClassName("set-review");
    const stars = new Array;

    const setStars = (rating) => {
      for (let i=0; i<rating; i++) {
          stars[i].innerHTML= "star";
      };
      for (let j=rating; j<5; j++ ){
          stars[j].innerHTML="star_border";
      };
    };

    const removeStars = (rating) => {
      for (let i=rating-1; i<5; i++) {
          stars[i].innerHTML= "star_border";
      };
    };

    for (let i=0; i<starElements.length; i++) {
        starElements[i].addEventListener('click', function(){
          let starValue = this.getAttribute("value");
          if (this.innerHTML == "star_border") {
              setStars(starValue);
              ratingField.value = starValue ;
          } else {
              removeStars(starValue);
              ratingField.value = starValue - 1;
          };    
        }, false);
        stars.push(starElements[i])
    }
</script>
{% endblock %}